name: boulder_lights_app 
version: 0.0.1
publish_to: none
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
authors: 
- Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.24
  get_it: ^5.0.3
  # sembast: '>=2.4.8'
  # tekartik_common_utils:
  #   git:
  #     url: git://github.com/tekartik/common_utils.dart
  #     ref: dart2

  flutter_bluetooth_serial: ^0.2.2  

  scoped_model: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
